// Generated by rstantools.  Do not edit by hand.

/*
    barmixR-main is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    barmixR-main is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with barmixR-main.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_barcode_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 81> locations_array__ =
  {" (found before start of program)",
  " (in 'barcode', line 40, column 2 to column 19)",
  " (in 'barcode', line 41, column 2 to column 25)",
  " (in 'barcode', line 42, column 2 to column 27)",
  " (in 'barcode', line 43, column 2 to column 30)",
  " (in 'barcode', line 44, column 2 to column 14)",
  " (in 'barcode', line 45, column 2 to column 17)",
  " (in 'barcode', line 46, column 2 to column 20)",
  " (in 'barcode', line 47, column 2 to column 30)",
  " (in 'barcode', line 48, column 2 to column 24)",
  " (in 'barcode', line 51, column 2 to column 28)",
  " (in 'barcode', line 52, column 2 to column 28)",
  " (in 'barcode', line 78, column 2 to column 24)",
  " (in 'barcode', line 79, column 2 to column 24)",
  " (in 'barcode', line 54, column 4 to column 43)",
  " (in 'barcode', line 55, column 4 to column 34)",
  " (in 'barcode', line 53, column 17 to line 56, column 3)",
  " (in 'barcode', line 53, column 2 to line 56, column 3)",
  " (in 'barcode', line 82, column 4 to column 55)",
  " (in 'barcode', line 83, column 4 to column 54)",
  " (in 'barcode', line 81, column 17 to line 84, column 3)",
  " (in 'barcode', line 81, column 2 to line 84, column 3)",
  " (in 'barcode', line 60, column 2 to column 48)",
  " (in 'barcode', line 61, column 2 to column 57)",
  " (in 'barcode', line 62, column 2 to column 29)",
  " (in 'barcode', line 63, column 2 to column 19)",
  " (in 'barcode', line 64, column 2 to column 25)",
  " (in 'barcode', line 65, column 2 to column 22)",
  " (in 'barcode', line 68, column 6 to column 35)",
  " (in 'barcode', line 69, column 6 to column 37)",
  " (in 'barcode', line 67, column 19 to line 70, column 5)",
  " (in 'barcode', line 67, column 4 to line 70, column 5)",
  " (in 'barcode', line 71, column 4 to column 54)",
  " (in 'barcode', line 66, column 17 to line 72, column 3)",
  " (in 'barcode', line 66, column 2 to line 72, column 3)",
  " (in 'barcode', line 74, column 4 to column 36)",
  " (in 'barcode', line 73, column 17 to line 75, column 3)",
  " (in 'barcode', line 73, column 2 to line 75, column 3)",
  " (in 'barcode', line 18, column 2 to column 17)",
  " (in 'barcode', line 19, column 2 to column 17)",
  " (in 'barcode', line 20, column 8 to column 9)",
  " (in 'barcode', line 20, column 11 to column 12)",
  " (in 'barcode', line 20, column 2 to column 20)",
  " (in 'barcode', line 21, column 2 to column 17)",
  " (in 'barcode', line 22, column 8 to column 9)",
  " (in 'barcode', line 22, column 2 to column 39)",
  " (in 'barcode', line 24, column 2 to column 25)",
  " (in 'barcode', line 25, column 2 to column 23)",
  " (in 'barcode', line 26, column 2 to column 28)",
  " (in 'barcode', line 27, column 2 to column 26)",
  " (in 'barcode', line 30, column 2 to column 28)",
  " (in 'barcode', line 31, column 2 to column 28)",
  " (in 'barcode', line 32, column 2 to column 31)",
  " (in 'barcode', line 33, column 2 to column 32)",
  " (in 'barcode', line 34, column 2 to column 71)",
  " (in 'barcode', line 35, column 2 to column 63)",
  " (in 'barcode', line 36, column 2 to column 83)",
  " (in 'barcode', line 37, column 2 to column 75)",
  " (in 'barcode', line 40, column 9 to column 10)",
  " (in 'barcode', line 40, column 11 to column 12)",
  " (in 'barcode', line 41, column 20 to column 21)",
  " (in 'barcode', line 42, column 20 to column 21)",
  " (in 'barcode', line 43, column 20 to column 21)",
  " (in 'barcode', line 44, column 9 to column 10)",
  " (in 'barcode', line 45, column 9 to column 10)",
  " (in 'barcode', line 45, column 11 to column 12)",
  " (in 'barcode', line 47, column 18 to column 19)",
  " (in 'barcode', line 47, column 21 to column 22)",
  " (in 'barcode', line 48, column 18 to column 19)",
  " (in 'barcode', line 51, column 8 to column 9)",
  " (in 'barcode', line 51, column 19 to column 20)",
  " (in 'barcode', line 52, column 8 to column 9)",
  " (in 'barcode', line 52, column 18 to column 19)",
  " (in 'barcode', line 78, column 8 to column 9)",
  " (in 'barcode', line 78, column 11 to column 12)",
  " (in 'barcode', line 79, column 8 to column 9)",
  " (in 'barcode', line 7, column 4 to column 33)",
  " (in 'barcode', line 8, column 4 to line 9, column 65)",
  " (in 'barcode', line 6, column 51 to line 10, column 3)",
  " (in 'barcode', line 12, column 4 to column 52)",
  " (in 'barcode', line 11, column 49 to line 13, column 3)"};
template <bool propto__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T1__>>
barmix_dm_lpmf(const std::vector<int>& y, const T1__& alpha_arg__,
               std::ostream* pstream__);
template <typename T0__, typename RNG,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
std::vector<int>
barmix_dm_rng(const T0__& alpha_arg__, const int& N, RNG& base_rng__,
              std::ostream* pstream__);
template <bool propto__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
stan::promote_args_t<stan::base_type_t<T1__>>
barmix_dm_lpmf(const std::vector<int>& y, const T1__& alpha_arg__,
               std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& alpha = stan::math::to_ref(alpha_arg__);
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ alpha_plus = DUMMY_VAR__;
    current_statement__ = 76;
    alpha_plus = stan::math::sum(alpha);
    current_statement__ = 77;
    return (((stan::math::lgamma(alpha_plus) +
           stan::math::sum(
             stan::math::lgamma(
               stan::math::add(alpha, stan::math::to_vector(y)))))
           - stan::math::lgamma((alpha_plus + stan::math::sum(y)))) -
           stan::math::sum(stan::math::lgamma(alpha)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename RNG,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
std::vector<int>
barmix_dm_rng(const T0__& alpha_arg__, const int& N, RNG& base_rng__,
              std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  const auto& alpha = stan::math::to_ref(alpha_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 79;
    return stan::math::multinomial_rng(
             stan::math::dirichlet_rng(alpha, base_rng__), N, base_rng__);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_barcode final : public model_base_crtp<model_barcode> {
private:
  int n;
  int C;
  std::vector<std::vector<int>> y;
  int K;
  std::vector<int> group;
  double psi_mean;
  double psi_sd;
  double varphi_mean;
  double varphi_sd;
  double default_psi_mean;
  double default_psi_sd;
  double default_varphi_mean;
  double default_varphi_sd;
  double final_psi_mean;
  double final_psi_sd;
  double final_varphi_mean;
  double final_varphi_sd;
public:
  ~model_barcode() {}
  model_barcode(stan::io::var_context& context__, unsigned int
                random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_barcode_namespace::model_barcode";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 38;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{});
      n = std::numeric_limits<int>::min();
      current_statement__ = 38;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 38;
      stan::math::check_greater_or_equal(function__, "n", n, 0);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "C", "int",
        std::vector<size_t>{});
      C = std::numeric_limits<int>::min();
      current_statement__ = 39;
      C = context__.vals_i("C")[(1 - 1)];
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "C", C, 0);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("y", "n", n);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("y", "C", C);
      current_statement__ = 42;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(n), static_cast<size_t>(C)});
      y = std::vector<std::vector<int>>(n,
            std::vector<int>(C, std::numeric_limits<int>::min()));
      {
        std::vector<int> y_flat__;
        current_statement__ = 42;
        y_flat__ = context__.vals_i("y");
        current_statement__ = 42;
        pos__ = 1;
        current_statement__ = 42;
        for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
          current_statement__ = 42;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 42;
            stan::model::assign(y, y_flat__[(pos__ - 1)],
              "assigning variable y", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 42;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 43;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 43;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 43;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("group", "n", n);
      current_statement__ = 45;
      context__.validate_dims("data initialization", "group", "int",
        std::vector<size_t>{static_cast<size_t>(n)});
      group = std::vector<int>(n, std::numeric_limits<int>::min());
      current_statement__ = 45;
      group = context__.vals_i("group");
      current_statement__ = 45;
      stan::math::check_greater_or_equal(function__, "group", group, 1);
      current_statement__ = 45;
      stan::math::check_less_or_equal(function__, "group", group, K);
      current_statement__ = 46;
      context__.validate_dims("data initialization", "psi_mean", "double",
        std::vector<size_t>{});
      psi_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 46;
      psi_mean = context__.vals_r("psi_mean")[(1 - 1)];
      current_statement__ = 46;
      stan::math::check_greater_or_equal(function__, "psi_mean", psi_mean, 0);
      current_statement__ = 47;
      context__.validate_dims("data initialization", "psi_sd", "double",
        std::vector<size_t>{});
      psi_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 47;
      psi_sd = context__.vals_r("psi_sd")[(1 - 1)];
      current_statement__ = 47;
      stan::math::check_greater_or_equal(function__, "psi_sd", psi_sd, 0);
      current_statement__ = 48;
      context__.validate_dims("data initialization", "varphi_mean", "double",
        std::vector<size_t>{});
      varphi_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 48;
      varphi_mean = context__.vals_r("varphi_mean")[(1 - 1)];
      current_statement__ = 48;
      stan::math::check_greater_or_equal(function__, "varphi_mean",
        varphi_mean, 0);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "varphi_sd", "double",
        std::vector<size_t>{});
      varphi_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 49;
      varphi_sd = context__.vals_r("varphi_sd")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "varphi_sd", varphi_sd,
        0);
      current_statement__ = 50;
      default_psi_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 50;
      default_psi_mean = 0;
      current_statement__ = 51;
      default_psi_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 51;
      default_psi_sd = 0.5;
      current_statement__ = 52;
      default_varphi_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 52;
      default_varphi_mean = 0;
      current_statement__ = 53;
      default_varphi_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 53;
      default_varphi_sd = 0.01;
      current_statement__ = 54;
      final_psi_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 54;
      final_psi_mean = (stan::math::is_nan(psi_mean) ? default_psi_mean : psi_mean);
      current_statement__ = 55;
      final_psi_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 55;
      final_psi_sd = (stan::math::is_nan(psi_sd) ? default_psi_sd : psi_sd);
      current_statement__ = 56;
      final_varphi_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 56;
      final_varphi_mean = (stan::math::is_nan(varphi_mean) ? default_varphi_mean : varphi_mean);
      current_statement__ = 57;
      final_varphi_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 57;
      final_varphi_sd = (stan::math::is_nan(varphi_sd) ? default_varphi_sd : varphi_sd);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("beta", "K", K);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("beta", "C", C);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("S", "C", C);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("psi", "C", C);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("varphi", "C", C);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("w", "C", C);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("mu", "K", K);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("mu", "C", C);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("sigma", "K", K);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("sigma", "C", C);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("nu", "K", K);
      current_statement__ = 69;
      stan::math::validate_non_negative_index("theta", "n", n);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("theta", "C", C);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("x_beta", "n", n);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("x_beta", "C", C);
      current_statement__ = 73;
      stan::math::validate_non_negative_index("y_rep", "n", n);
      current_statement__ = 74;
      stan::math::validate_non_negative_index("y_rep", "C", C);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("log_lik", "n", n);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (K * C) + C + C + C + C + (K * C) + 1 + (K * C) + K;
  }
  inline std::string model_name() const final {
    return "model_barcode";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_barcode_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,-1> beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, C, DUMMY_VAR__);
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(K, C);
      Eigen::Matrix<local_scalar_t__,-1,1> S =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      current_statement__ = 2;
      S = in__.template read_constrain_lb<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, C);
      Eigen::Matrix<local_scalar_t__,-1,1> psi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      current_statement__ = 3;
      psi = in__.template read_constrain_lb<
              Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, C);
      Eigen::Matrix<local_scalar_t__,-1,1> varphi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      current_statement__ = 4;
      varphi = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 C);
      Eigen::Matrix<local_scalar_t__,-1,1> w =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      current_statement__ = 5;
      w = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(C);
      Eigen::Matrix<local_scalar_t__,-1,-1> mu =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, C, DUMMY_VAR__);
      current_statement__ = 6;
      mu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(K, C);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 7;
      tau = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<local_scalar_t__,-1,-1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, C, DUMMY_VAR__);
      current_statement__ = 8;
      sigma = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(0, lp__,
                K, C);
      Eigen::Matrix<local_scalar_t__,-1,1> nu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 9;
      nu = in__.template read_constrain_lb<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, K);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> theta =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(n,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__));
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> x_beta =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(n,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__));
      current_statement__ = 17;
      for (int j = 1; j <= n; ++j) {
        current_statement__ = 14;
        stan::model::assign(x_beta,
          stan::math::to_vector(
            stan::model::rvalue(beta, "beta",
              stan::model::index_uni(
                stan::model::rvalue(group, "group", stan::model::index_uni(j))),
              stan::model::index_omni())), "assigning variable x_beta",
          stan::model::index_uni(j));
        current_statement__ = 15;
        stan::model::assign(theta,
          stan::math::softmax(
            stan::model::rvalue(x_beta, "x_beta", stan::model::index_uni(j))),
          "assigning variable theta", stan::model::index_uni(j));
      }
      current_statement__ = 10;
      stan::math::check_simplex(function__, "theta", theta);
      {
        current_statement__ = 22;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(psi,
                         final_psi_mean, final_psi_sd));
        current_statement__ = 23;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(varphi,
                         final_varphi_mean, final_varphi_sd));
        current_statement__ = 24;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(S, psi, varphi));
        current_statement__ = 25;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(w, 0, 1));
        current_statement__ = 26;
        lp_accum__.add(stan::math::gumbel_lpdf<propto__>(tau, 0.5, 0.1));
        current_statement__ = 27;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(nu, 1));
        current_statement__ = 34;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 31;
          for (int l = 1; l <= C; ++l) {
            current_statement__ = 28;
            lp_accum__.add(stan::math::normal_lpdf<propto__>(
                             stan::model::rvalue(mu, "mu",
                               stan::model::index_uni(k),
                               stan::model::index_uni(l)),
                             stan::model::rvalue(w, "w",
                               stan::model::index_uni(l)), tau));
            current_statement__ = 29;
            lp_accum__.add(stan::math::gumbel_lpdf<propto__>(
                             stan::model::rvalue(sigma, "sigma",
                               stan::model::index_uni(k),
                               stan::model::index_uni(l)), 0.5, 0.1));
          }
          current_statement__ = 32;
          lp_accum__.add(stan::math::student_t_lpdf<propto__>(
                           stan::model::rvalue(beta, "beta",
                             stan::model::index_uni(k),
                             stan::model::index_omni()),
                           stan::model::rvalue(nu, "nu",
                             stan::model::index_uni(k)),
                           stan::model::rvalue(mu, "mu",
                             stan::model::index_uni(k),
                             stan::model::index_omni()),
                           stan::model::rvalue(sigma, "sigma",
                             stan::model::index_uni(k),
                             stan::model::index_omni())));
        }
        current_statement__ = 37;
        for (int j = 1; j <= n; ++j) {
          current_statement__ = 35;
          lp_accum__.add(barmix_dm_lpmf<propto__>(
                           stan::model::rvalue(y, "y",
                             stan::model::index_uni(j)),
                           stan::math::elt_multiply(S,
                             stan::model::rvalue(theta, "theta",
                               stan::model::index_uni(j))), pstream__));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_barcode_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,-1> beta =
        Eigen::Matrix<double,-1,-1>::Constant(K, C,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(K, C);
      Eigen::Matrix<double,-1,1> S =
        Eigen::Matrix<double,-1,1>::Constant(C,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      S = in__.template read_constrain_lb<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, C);
      Eigen::Matrix<double,-1,1> psi =
        Eigen::Matrix<double,-1,1>::Constant(C,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      psi = in__.template read_constrain_lb<
              Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, C);
      Eigen::Matrix<double,-1,1> varphi =
        Eigen::Matrix<double,-1,1>::Constant(C,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      varphi = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 C);
      Eigen::Matrix<double,-1,1> w =
        Eigen::Matrix<double,-1,1>::Constant(C,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      w = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(C);
      Eigen::Matrix<double,-1,-1> mu =
        Eigen::Matrix<double,-1,-1>::Constant(K, C,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      mu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(K, C);
      double tau = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      tau = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<double,-1,-1> sigma =
        Eigen::Matrix<double,-1,-1>::Constant(K, C,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 8;
      sigma = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(0, lp__,
                K, C);
      Eigen::Matrix<double,-1,1> nu =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 9;
      nu = in__.template read_constrain_lb<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, K);
      std::vector<Eigen::Matrix<double,-1,1>> theta =
        std::vector<Eigen::Matrix<double,-1,1>>(n,
          Eigen::Matrix<double,-1,1>::Constant(C,
            std::numeric_limits<double>::quiet_NaN()));
      std::vector<Eigen::Matrix<double,-1,1>> x_beta =
        std::vector<Eigen::Matrix<double,-1,1>>(n,
          Eigen::Matrix<double,-1,1>::Constant(C,
            std::numeric_limits<double>::quiet_NaN()));
      out__.write(beta);
      out__.write(S);
      out__.write(psi);
      out__.write(varphi);
      out__.write(w);
      out__.write(mu);
      out__.write(tau);
      out__.write(sigma);
      out__.write(nu);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 17;
      for (int j = 1; j <= n; ++j) {
        current_statement__ = 14;
        stan::model::assign(x_beta,
          stan::math::to_vector(
            stan::model::rvalue(beta, "beta",
              stan::model::index_uni(
                stan::model::rvalue(group, "group", stan::model::index_uni(j))),
              stan::model::index_omni())), "assigning variable x_beta",
          stan::model::index_uni(j));
        current_statement__ = 15;
        stan::model::assign(theta,
          stan::math::softmax(
            stan::model::rvalue(x_beta, "x_beta", stan::model::index_uni(j))),
          "assigning variable theta", stan::model::index_uni(j));
      }
      current_statement__ = 10;
      stan::math::check_simplex(function__, "theta", theta);
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            out__.write(theta[(sym2__ - 1)][(sym1__ - 1)]);
          }
        }
        for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            out__.write(x_beta[(sym2__ - 1)][(sym1__ - 1)]);
          }
        }
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      std::vector<std::vector<int>> y_rep =
        std::vector<std::vector<int>>(n,
          std::vector<int>(C, std::numeric_limits<int>::min()));
      std::vector<double> log_lik =
        std::vector<double>(n, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 21;
      for (int j = 1; j <= n; ++j) {
        current_statement__ = 18;
        stan::model::assign(y_rep,
          barmix_dm_rng(
            stan::math::elt_multiply(S,
              stan::model::rvalue(theta, "theta", stan::model::index_uni(j))),
            stan::math::sum(
              stan::model::rvalue(y, "y", stan::model::index_uni(j))),
            base_rng__, pstream__), "assigning variable y_rep",
          stan::model::index_uni(j));
        current_statement__ = 19;
        stan::model::assign(log_lik,
          barmix_dm_lpmf<false>(
            stan::model::rvalue(y, "y", stan::model::index_uni(j)),
            stan::math::elt_multiply(S,
              stan::model::rvalue(theta, "theta", stan::model::index_uni(j))),
            pstream__), "assigning variable log_lik",
          stan::model::index_uni(j));
      }
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          out__.write(y_rep[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, C, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(K, C),
        "assigning variable beta");
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> S =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(S,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(C),
        "assigning variable S");
      out__.write_free_lb(0, S);
      Eigen::Matrix<local_scalar_t__,-1,1> psi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(psi,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(C),
        "assigning variable psi");
      out__.write_free_lb(0, psi);
      Eigen::Matrix<local_scalar_t__,-1,1> varphi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(varphi,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(C),
        "assigning variable varphi");
      out__.write_free_lb(0, varphi);
      Eigen::Matrix<local_scalar_t__,-1,1> w =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(w,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(C),
        "assigning variable w");
      out__.write(w);
      Eigen::Matrix<local_scalar_t__,-1,-1> mu =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, C, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(mu,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(K, C),
        "assigning variable mu");
      out__.write(mu);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 7;
      tau = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, tau);
      Eigen::Matrix<local_scalar_t__,-1,-1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, C, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(sigma,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(K, C),
        "assigning variable sigma");
      out__.write_free_lb(0, sigma);
      Eigen::Matrix<local_scalar_t__,-1,1> nu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 9;
      stan::model::assign(nu,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable nu");
      out__.write_free_lb(0, nu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(C)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "S", "double",
        std::vector<size_t>{static_cast<size_t>(C)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "psi", "double",
        std::vector<size_t>{static_cast<size_t>(C)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "varphi", "double",
        std::vector<size_t>{static_cast<size_t>(C)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "w", "double",
        std::vector<size_t>{static_cast<size_t>(C)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(C)});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "tau", "double",
        std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(C)});
      current_statement__ = 9;
      context__.validate_dims("parameter initialization", "nu", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, C, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 1;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 1;
            stan::model::assign(beta, beta_flat__[(pos__ - 1)],
              "assigning variable beta", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 1;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> S =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> S_flat__;
        current_statement__ = 2;
        S_flat__ = context__.vals_r("S");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(S, S_flat__[(pos__ - 1)],
            "assigning variable S", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, S);
      Eigen::Matrix<local_scalar_t__,-1,1> psi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> psi_flat__;
        current_statement__ = 3;
        psi_flat__ = context__.vals_r("psi");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(psi, psi_flat__[(pos__ - 1)],
            "assigning variable psi", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, psi);
      Eigen::Matrix<local_scalar_t__,-1,1> varphi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> varphi_flat__;
        current_statement__ = 4;
        varphi_flat__ = context__.vals_r("varphi");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(varphi, varphi_flat__[(pos__ - 1)],
            "assigning variable varphi", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, varphi);
      Eigen::Matrix<local_scalar_t__,-1,1> w =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(C, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> w_flat__;
        current_statement__ = 5;
        w_flat__ = context__.vals_r("w");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
          current_statement__ = 5;
          stan::model::assign(w, w_flat__[(pos__ - 1)],
            "assigning variable w", stan::model::index_uni(sym1__));
          current_statement__ = 5;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(w);
      Eigen::Matrix<local_scalar_t__,-1,-1> mu =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, C, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> mu_flat__;
        current_statement__ = 6;
        mu_flat__ = context__.vals_r("mu");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
          current_statement__ = 6;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 6;
            stan::model::assign(mu, mu_flat__[(pos__ - 1)],
              "assigning variable mu", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 6;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(mu);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 7;
      tau = context__.vals_r("tau")[(1 - 1)];
      out__.write_free_lb(0, tau);
      Eigen::Matrix<local_scalar_t__,-1,-1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, C, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigma_flat__;
        current_statement__ = 8;
        sigma_flat__ = context__.vals_r("sigma");
        current_statement__ = 8;
        pos__ = 1;
        current_statement__ = 8;
        for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
          current_statement__ = 8;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 8;
            stan::model::assign(sigma, sigma_flat__[(pos__ - 1)],
              "assigning variable sigma", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 8;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_lb(0, sigma);
      Eigen::Matrix<local_scalar_t__,-1,1> nu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> nu_flat__;
        current_statement__ = 9;
        nu_flat__ = context__.vals_r("nu");
        current_statement__ = 9;
        pos__ = 1;
        current_statement__ = 9;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 9;
          stan::model::assign(nu, nu_flat__[(pos__ - 1)],
            "assigning variable nu", stan::model::index_uni(sym1__));
          current_statement__ = 9;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, nu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta", "S", "psi", "varphi", "w",
                "mu", "tau", "sigma", "nu"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"theta", "x_beta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"y_rep", "log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(K),
                                                 static_cast<size_t>(C)},
                std::vector<size_t>{static_cast<size_t>(C)},
                std::vector<size_t>{static_cast<size_t>(C)},
                std::vector<size_t>{static_cast<size_t>(C)},
                std::vector<size_t>{static_cast<size_t>(C)},
                std::vector<size_t>{static_cast<size_t>(K),
                  static_cast<size_t>(C)}, std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(K),
                  static_cast<size_t>(C)},
                std::vector<size_t>{static_cast<size_t>(K)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n),
               static_cast<size_t>(C)},
             std::vector<size_t>{static_cast<size_t>(n),
               static_cast<size_t>(C)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n),
               static_cast<size_t>(C)},
             std::vector<size_t>{static_cast<size_t>(n)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      param_names__.emplace_back(std::string() + "S" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      param_names__.emplace_back(std::string() + "psi" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      param_names__.emplace_back(std::string() + "varphi" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      param_names__.emplace_back(std::string() + "w" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "mu" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "tau");
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "sigma" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "nu" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "theta" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "x_beta" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "y_rep" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      param_names__.emplace_back(std::string() + "S" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      param_names__.emplace_back(std::string() + "psi" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      param_names__.emplace_back(std::string() + "varphi" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      param_names__.emplace_back(std::string() + "w" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "mu" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "tau");
    for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "sigma" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "nu" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= (C - 1); ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "theta" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "x_beta" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "y_rep" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"S\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"psi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"varphi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"x_beta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(C) + ",\"element_type\":{\"name\":\"int\"}}},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"S\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"psi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"varphi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(C) + "},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string((C -1)) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"x_beta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(C) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(C) + ",\"element_type\":{\"name\":\"int\"}}},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((((K * C) + C) + C) + C) + C) + (K *
      C)) + 1) + (K * C)) + K);
    const size_t num_transformed = emit_transformed_parameters * (((n * C) +
      (n * C)));
    const size_t num_gen_quantities = emit_generated_quantities * (((n * C) +
      n));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((((K * C) + C) + C) + C) + C) + (K *
      C)) + 1) + (K * C)) + K);
    const size_t num_transformed = emit_transformed_parameters * (((n * C) +
      (n * C)));
    const size_t num_gen_quantities = emit_generated_quantities * (((n * C) +
      n));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_barcode_namespace::model_barcode;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_barcode_namespace::profiles__;
}
#endif
#endif
